version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: 'monthly'
    labels:
      - "x:size/tiny"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: 'monthly'
    labels:
      - "x:size/small"

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: 'monthly'
    labels:
      - "x:size/small"
